name: test

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.*"
      - "COPYING"
  pull_request:
    paths-ignore:
      - "README.*"
      - "COPYING"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ["2.0.4", "stable"]
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - run: nimble install -Y
      - run: testament p 'tests/*.nim'

